apiVersion: policy/v1
kind: PodSecurityPolicy
metadata:
  name: restricted-policy
spec:
  privileged: false
  allowPrivilegeEscalation: false
  runAsUser:
    rule: MustRunAsNonRoot
  volumes:
    - "configMap"
    - "emptyDir"
    - "persistentVolumeClaim"
