name: Secure CI/CD Deployment

on:
  push:
    branches:
      - main

permissions:
  security-events: write

jobs:
  security-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run CodeQL Security Scan
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Install Conftest
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/open-policy-agent/conftest/releases/latest | jq -r .tag_name)
          curl -LO https://github.com/open-policy-agent/conftest/releases/download/${LATEST_VERSION}/conftest_${LATEST_VERSION}_Linux_x86_64.tar.gz
          tar -xvzf conftest_${LATEST_VERSION}_Linux_x86_64.tar.gz
          sudo mv conftest /usr/local/bin/

      - name: Run Conftest on Kubernetes Manifests
        run: conftest test infra/deployment.yml --policy policy/

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: security-checks
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Minikube
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          chmod +x minikube && sudo mv minikube /usr/local/bin/
          minikube start --driver=docker

      - name: Set up kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl && sudo mv kubectl /usr/local/bin/

      - name: Build Docker Image
        run: |
          eval $(minikube -p minikube docker-env)
          docker build -t dahunsij/secure_mono:latest .

      - name: Scan Image with Trivy
        run: trivy image dahunsij/secure_mono:latest

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f infra/deployment.yml
          kubectl apply -f infra/service.yml
          kubectl apply -f infra/ingress.yml

      - name: Verify Deployment
        run: |
          kubectl get pods -o wide
